[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  source = "git@github.com:nicolaferraro/operator-sdk.git"
  # Using a fork until changes are merged back
  branch = "syndesis-changes"
  # version = "=v0.0.5"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "github.com/openshift/origin"
  version = "v3.9.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.9.3"

[[constraint]]
  name = "github.com/go-bindata/go-bindata"
  version = "1.0.0"
