apiVersion: apps/v1
kind: Deployment
metadata:
  name: syndesis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: syndesis-operator
  template:
    metadata:
      labels:
        name: syndesis-operator
    spec:
      containers:
        - name: syndesis-operator
          image: rhuss/syndesis-operator
          command:
          - syndesis-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
